# Generated by Django 3.2.8 on 2021-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20211103_1311'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstages',
            name='report',
        ),
        migrations.AddField(
            model_name='workstages',
            name='report',
            field=models.ManyToManyField(related_name='ReportStage', to='bugs.Report'),
        ),
    ]
