# Generated by Django 3.2.8 on 2021-11-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20211103_1311'),
        ('stages', '0002_auto_20211103_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstages',
            name='report',
        ),
        migrations.AddField(
            model_name='workstages',
            name='report',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReportStage', to='bugs.report'),
            preserve_default=False,
        ),
    ]
