# Generated by Django 3.2.8 on 2021-11-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20211103_1311'),
        ('stages', '0003_auto_20211103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstages',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportStage', to='bugs.report'),
        ),
    ]
