# Generated by Django 3.2.8 on 2021-11-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_stages'),
        ('stages', '0004_alter_workstages_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstages',
            name='report',
        ),
        migrations.AddField(
            model_name='workstages',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportStage', to='projects.project'),
        ),
    ]
