# Generated by Django 3.2.8 on 2021-10-31 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('reports', models.ManyToManyField(related_name='ProjectReports', to='bugs.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
