# Generated by Django 3.2.8 on 2021-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_workstages_report'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.ManyToManyField(related_name='ProjectStages', to='stages.WorkStages'),
        ),
    ]
