# Generated by Django 3.2.8 on 2021-11-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReportStage', to='stages.workstages'),
        ),
        migrations.DeleteModel(
            name='WorkStages',
        ),
    ]
