# Generated by Django 3.2.8 on 2021-11-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('bugs', '0002_auto_20211103_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(related_name='ReportTags', to='tags.Tag'),
        ),
    ]
